In [26]:
import os 
import pandas as pd
import numpy as np
import pickle 
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score, make_scorer, confusion_matrix

In [27]:
def classification_report_with_accuracy_score(y_true, y_pred):
    originalclass.extend(y_true)
    predictedclass.extend(y_pred)
    return accuracy_score(y_true, y_pred) # return accuracy score


<h1> Training ML <h1>

In [34]:
mapping_label =['Bronchiectasis','Bronchiolitis', 'LRTI', 'Pneumonia','URTI','Asthma']

In [29]:
with open('../../data/data_model/data_dict.pkl','rb') as f:
    data = pickle.load(f)

In [30]:
clf = RandomForestClassifier(n_estimators = 500, 
    max_depth=2,
    class_weight = 'balanced', 
    random_state=0
    )

In [57]:
X=data['features']
y = pd.Series(data['label'])
y = y.replace(mapping_label,'respiratory_infection')
y = y.values

In [55]:
skf = StratifiedKFold(n_splits=10)
cv =  skf.split(X, y)
originalclass = []
predictedclass = []
score = cross_val_score(clf, X=X, y=y, cv=cv, scoring=make_scorer(classification_report_with_accuracy_score))

c = classification_report(originalclass, predictedclass)
print(c)

                       precision    recall  f1-score   support

                 COPD       0.98      0.94      0.96       793
              Healthy       0.41      0.54      0.47        35
respiratory_infection       0.54      0.66      0.59        92

             accuracy                           0.90       920
            macro avg       0.64      0.72      0.67       920
         weighted avg       0.91      0.90      0.90       920



In [43]:
import matplotlib.pyplot as plt
import seaborn as sns

x = confusion_matrix(originalclass, predictedclass)
print(x)

[[745   9  39]
 [  2  19  14]
 [ 13  18  61]]
