In [11]:
import pandas as pd
import numpy as np

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score, make_scorer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold

In [12]:
def classification_report_with_accuracy_score(y_true, y_pred):
    originalclass.extend(y_true)
    predictedclass.extend(y_pred)
    return accuracy_score(y_true, y_pred) # return accuracy score

In [13]:
df_info = pd.read_csv('../../data/info_dataset.csv')
df_info.columns

Index(['Unnamed: 0', 'Participant_ID', 'Age', 'Sex', 'Adult BMI (kg/m2)',
       'Child Weight (kg)', 'Child Height (cm)', 'Outcome', 'filename',
       'train_test_split', 'wheeze', 'crackle', 'recording_type'],
      dtype='object')

In [14]:
df_info['Outcome'].value_counts()

COPD              793
Pneumonia          37
Healthy            35
URTI               23
Bronchiectasis     16
Bronchiolitis      13
LRTI                2
Asthma              1
Name: Outcome, dtype: int64

In [15]:
label_tochange = ['Pneumonia','URTI','Bronchiectasis','Bronchiolitis','LRTI','Asthma']
df_info['Outcome'] = df_info['Outcome'].replace(label_tochange,'Respiratory_infection')

In [16]:

skf = StratifiedKFold(n_splits=10)
X=df_info[['wheeze','crackle']]
y = df_info.Outcome

In [32]:
clf  = RandomForestClassifier(
    n_estimators=1000,
    max_depth=10,
    class_weight = 'balanced', 
    )

In [33]:
cv =  skf.split(X, y)
originalclass = []
predictedclass = []
score = cross_val_score(clf, X=X, y=y, cv=cv, scoring=make_scorer(classification_report_with_accuracy_score))

c = classification_report(originalclass, predictedclass)
print(c)

                       precision    recall  f1-score   support

                 COPD       0.93      0.60      0.73       793
              Healthy       0.10      0.86      0.18        35
Respiratory_infection       0.10      0.12      0.11        92

             accuracy                           0.56       920
            macro avg       0.38      0.52      0.34       920
         weighted avg       0.81      0.56      0.64       920



In [34]:
print(confusion_matrix(originalclass,predictedclass))

[[474 224  95]
 [  3  30   2]
 [ 35  46  11]]
