In [34]:
import pandas as pd
import numpy as np

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, accuracy_score, make_scorer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold

In [35]:
def classification_report_with_accuracy_score(y_true, y_pred):
    originalclass.extend(y_true)
    predictedclass.extend(y_pred)
    return accuracy_score(y_true, y_pred) # return accuracy score

In [36]:
df_info = pd.read_csv('../../data/info_dataset.csv')
df_info.columns

Index(['Unnamed: 0', 'Participant_ID', 'Age', 'Sex', 'Adult BMI (kg/m2)',
       'Child Weight (kg)', 'Child Height (cm)', 'Outcome', 'filename',
       'wheeze', 'crackle', 'recording_type'],
      dtype='object')

In [37]:
df_info['Outcome'].value_counts()

COPD              793
Pneumonia          38
Healthy            35
URTI               23
Bronchiectasis     16
Bronchiolitis      13
LRTI                2
Asthma              1
Name: Outcome, dtype: int64

In [38]:
label_tochange = ['URTI','Bronchiolitis','LRTI','Asthma']
df_info['Outcome'] = df_info['Outcome'].replace(label_tochange,'Respiratory_infection')
label_tochange = ['Pneumonia','COPD','Bronchiectasis']
df_info['Outcome'] = df_info['Outcome'].replace(label_tochange,'COPDX')

In [39]:
df_info = df_info.dropna(subset=['wheeze','crackle'])

In [40]:
df_info['wheeze'] = np.where(df_info['wheeze']>0,1,0)
df_info['crackle'] = np.where(df_info['crackle']>0,1,0)


In [41]:

skf = StratifiedKFold(n_splits=5)
X=df_info[['wheeze','crackle']]
y = df_info.Outcome

In [42]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
clf = RandomForestClassifier(n_estimators =100, 
    max_depth=1,
    class_weight = 'balanced', 
    random_state=0
    )
clf.fit(X, y)

RandomForestClassifier(class_weight='balanced', max_depth=1, random_state=0)

In [43]:
cv =  skf.split(X, y)
originalclass = []
predictedclass = []
score = cross_val_score(clf, X=X, y=y, cv=cv, scoring=make_scorer(classification_report_with_accuracy_score))

c = classification_report(originalclass, predictedclass)
print(c)

                       precision    recall  f1-score   support

                COPDX       0.96      0.57      0.71       846
              Healthy       0.10      0.80      0.18        35
Respiratory_infection       0.06      0.21      0.09        39

             accuracy                           0.56       920
            macro avg       0.37      0.52      0.33       920
         weighted avg       0.89      0.56      0.67       920



In [44]:
print(confusion_matrix(originalclass,predictedclass))

[[480 239 127]
 [  6  28   1]
 [ 15  16   8]]
